wandb_version: 1

lr:
  desc: null
  value: 0.001337149225551439
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736772467
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.11.11
      5: 0.19.2
      8:
      - 5
      13: darwin-x86_64
batch-size:
  desc: null
  value: 32
