program: train.py
name: sweepdemo
project: corrupt_mnist
entity: s204605-danmarks-tekniske-universitet-dtu
method: random
metric:
  goal: minimize
  name: validation_loss
parameters:
  lr:
    min: 0.0001
    max: 0.1
    distribution: log_uniform_values
  batch-size:
    values: [16, 32, 64]
  epochs:
    values: [5, 10, 15]
run_cap: 10
