name: "Run tests" # Name of the workflow

on: # This workflow is triggered on pushes to the repository.
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs: 
  build:

    runs-on: ubuntu-latest # virtual machine where the workflow will execute

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v
